pool:
  name: MobileTeamPool

trigger:
  branches:
    exclude:
    - '*'
  tags:
    include:
    - '*'

steps:
  - script: |
      cd ios_framework
      ./build_ios_framework.sh --source-dir=$(dirname "$(realpath "$PWD")") --output-dir="$PWD/artifact" --name=$(Build.SourceBranchName)
    displayName: 'Build framework'

  - task: CopyFiles@2
    displayName: 'Copy Files to build directory'
    inputs:
      SourceFolder: './ios_framework/artifact'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: GitHubRelease@1
    displayName: 'https://github.com/DmitriyAnd/pjproject.git'
    inputs:
      gitHubConnection: 'Github PJSIP'
      title: 'PJSIP iOS $(Build.SourceBranchName)'
      isDraft: true
      addChangeLog: false